


<div class="col-md-10 col-md-offset-1">


			<!--header-->	

            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">LISTADOS DE EMPRESAS PRODUCTORAS</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                  </div>
                </div>
              </div>





              <!-- body-->

              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th><em class="fa fa-cog"></em></th>
                        <th class="hidden-xs">RIF</th>
                        <th>RAZON SOCIAL</th>
                        <th>TIPO DE PRODUCTOR</th>
                    </tr> 
                  </thead>
                
                  
                <tbody>

<!--ciclo............................................................................................ -->
							<?php for ($i=0; $i < count($this->lista)  ; $i++):?>	
                          <tr>
                            <td align="center">
                              <a class="btn btn-default"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a>
                            
                            </td>

                            

                            <td class="hidden-xs"><?php echo $this->lista[$i]['rif'] ?></td>
                            <td><?php echo $this->lista[$i]['razon_social'] ?></td>
                            <td><?php echo $this->lista[$i]['tipo'] ?></td>



                           </tr>


                          	<?php endfor; ?>
<!--end ciclo............................................................................................ -->
                        </tbody>
                </table>
            
              </div>

				<!-- footer -->

              <div class="panel-footer">
                <div class="row">
                  <div class="col col-xs-4">Page 1 of 5
                  </div>
                  <div class="col col-xs-8">
                    <ul class="pagination hidden-xs pull-right">
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                    </ul>
                    <ul class="pagination visible-xs pull-right">
                        <li><a href="#">«</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                  </div>
                </div>
              </div>
          





	
</div>
		