<div class="col-md-8 col-md-offset-2">
	
	<form>
	  <div class="form-group">
	    <label for="Cedula">Cedula</label>
	    <input type="text" class="form-control" id="cedula" placeholder="Cedula">
	  </div>

	  <div class="form-group">
	    <label for="Nombres">Nombres</label>
	    <input type="text" class="form-control" id="nombres" placeholder="nombres">
	  </div>

	  <div class="form-group">
	    <label for="apellidos">Apellidos</label>
	    <input type="text" class="form-control" id="apellidos" placeholder="apellidos">
	  </div>

	  <div class="form-group">
	    <label for="telefono">Telefono</label>
	    <input type="text" class="form-control" id="telefono" placeholder="telefono">
	  </div>

	  <div class="form-group">
	    <label for="direccion">Direccion</label>
	    <input type="text" class="form-control" id="direccion" placeholder="direccion">
	  </div>

	  <div class="form-group">
	    <label for="productora">Productora</label>
	    <select name="" id="" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<?php for ($i=0; $i < count($this->_empresas) ; $i++) { ?>
	    		<option value="<?php echo $this->_empresas[$i]['id_emp'] ?>"><?php echo $this->_empresas[$i]['razon_social'] ?></option>
	    	<?php } ?>
	    </select>
		
	  <button type="button" id="guardar" class="btn btn-default">Guardar</button>
	</form>

</div>
		