<div id="titulo">registro de socios y/o encargado</div>
<div class="col-md-6 col-md-offset-3">


	
	<form id="agregar">
	  <div class="form-group">
	    <label for="nacionalidad">Nacionalidad</label>
	    <select id="nacionalidad" class="form-control">
	    	
	    	<option value="V">
	    		V
	    	</option>
	    	<option value="V">
	    		E
	    	</option>
	    </select>

	  
	  </div>
	  <div class="form-group">
	    <label for="Cedula">Cedula</label>
	    <input type="text" class="form-control" id="cedula" placeholder="Cedula">
	  </div>

	  <div class="form-group">
	    <label for="rif">Rif</label>
	    <input type="text" class="form-control" id="rif" placeholder="RIF">
	  </div>

	  <div class="form-group">
	    <label for="Nombres">Nombres</label>
	    <input type="text" class="form-control" id="nombres" placeholder="nombres">
	  </div>

	  <div class="form-group">
	    <label for="apellidos">Apellidos</label>
	    <input type="text" class="form-control" id="apellidos" placeholder="apellidos">
	  </div>

	  <div class="form-group">
	    <label for="telefono">Telefono</label>
	    <input type="text" class="form-control" id="telefono" placeholder="telefono">
	  </div>

	  <div class="form-group">
	    <label for="direccion">Direccion</label>
	    <input type="text" class="form-control" id="direccion" placeholder="direccion">
	  </div>

	  <div class="form-group">
	    <label for="codigo">codigo del carnet de la patria</label>
	    <input type="text" class="form-control" id="codigo" placeholder="codigo">
	  </div>

	  <div class="form-group">
	    <label for="serial">serial del carnet de la patria</label>
	    <input type="text" class="form-control" id="serial" placeholder="serial">
	  </div>

	  <div class="form-group">
	    <label for=""> ¿posee certificado medico?</label>
	    <select name="" id="certificado_medico" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option value="SI">-SI-</option>
	    	<option value="NO">-NO-</option>
	    </select>
	 </div>
	 

	  <div class="form-group">
	    <label for="productora">Productora</label>
	    <select name="" id="productora" class="form-control">
	    	 	
	    	<?php for ($i=0; $i < count($this->_empresas) ; $i++) { ?>
	    		<option value="<?php echo $this->_empresas[$i]['id_emp'] ?>"><?php echo $this->_empresas[$i]['razon_social'] ?></option>
	    	<?php } ?>
	    </select>
		
	  <button type="button" id="guardar" class="btn btn-default">Guardar</button>
	  <button type="button" id="inicio" class="btn btn-default">Inicio</button>
	</form>

</div>
		