<div class="col-md-12">
	
	<form>
	  <div class="form-group">
	    <label for="Cedula">Cedula</label>
	    <input type="text" class="form-control" id="cedula" placeholder="Cedula">
	  </div>

	  <div class="form-group">
	    <label for="Nombre">Nombre</label>
	    <input type="text" class="form-control" id="nombre" placeholder="nombre">
	  </div>

	


	  <button type="button" class="btn btn-default">Guardar</button>
	</form>

</div>
		
		
		

