
		
		
<div class="col-md-6 col-md-offset-3">
	
	
		<form id="agregar" action="">
	  <div class="form-group">
	    <label for="RIF">RIF</label>
	    <input type="text" class="form-control" id="rif" placeholder="RIF">
	  </div>

	  <div class="form-group">
	    <label for="Razon_Social">Razon Social</label>
	    <input type="text" class="form-control" id="razon_social" placeholder="Razon Social">
	  </div>

	  <div class="form-group">
	    <label for="Nro_de_Registro">Nro de Registro</label>
	    <input type="text" class="form-control" id="nro_de_registro" placeholder="Rro de Registro">
	  </div>
	
	  <div class="form-group">
	    <label for="tipo">tipo de productor</label>
	    <select name="" id="tipo" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option value="Panadero">-Panadero-</option>
	    	<option value="Empanadero">-Empanadero-</option>
	    	<option value="Pasteleria">-Pasteleria-</option>
	    	<option value="Dulceria">-Dulceria-</option>
	    	<option value="Heladeria">Heladeria-</option>
	    	<option value="Otros">-Otros-</option>
	    </select>
	 </div>


	 <div class="form-group">
	    <label for="">Municipio</label>
	    <select name="" id="municipio" class="form-control">
	    	<option  value="">-seleccione-</option>
		<?php 
			for ($i=0; $i < count($this->_municipios) ; $i++) { ?>

				<option value="<?php echo $this->_municipios[$i]["id_municipio"] ?>"><?php echo $this->_municipios[$i]["municipio"] ?></option>

		<?php 		
			}
		 ?>
	    </select>
	 </div>

	 <div class="form-group">
	    <label for="Parroquia">Parroquia</label>
	    <select name="" id="parroquia" class="form-control">
	    	<option value="">-Seleccione-</option>
	    	
	    </select>
	 </div>

	  <div class="form-group">
	    <label for="Direccion">Direccion</label>
	    <input type="text" class="form-control" id="direccion" placeholder="Direccion">
	  </div>

	  <div class="form-group">
	    <label for=""> ¿posee certificados del inces?</label>
	    <select name="" id="poseec" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option value="SI">-SI-</option>
	    	<option value="NO">-NO-</option>
	    </select>
	 </div>
	 	<div class="form-group">
	    <label for="">¿posee permiso sanitario?</label>
	    <select name="" id="poseep" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option value="SI">-SI-</option>
	    	<option value="NO">-NO-</option>
	    </select>
	 </div> 	

	
	
	  <button type="button" id="guardar" class="btn btn-default">Guardar</button>
	   <button type="button" id="inicio" class="btn btn-default">Inicio</button>
	</form>

	</div>
		
