<div class="col-md-12">
	
<div id="text" class="col-md-8 col-md-offset-2">Sistema integrado de registro de productores y productoras del Estado Sucre.</div>

<div id="regis_de_emp-productora" class="col-md-4 col-md-offset-1">
	
	Registro de empresas productoras 


</div>
<a href="<?php echo BASE_URL;?>regis_per  ">
<div id="regis_de_personal" class="col-md-4 col-md-offset-2">
	
	Registro de encargados y/o socios  

</div>
</a>

</div>

		
		

